version: '3'
services:
  kusama_alice:
    build:
      context: .
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    image: ubuntu:20.04
    volumes:
      - .:/usr/src/polkafoundry
    command: polkadot --chain /usr/local/kusama-local.json --alice --pruning archive --unsafe-ws-external --rpc-cors all --rpc-methods Unsafe
    networks:
      polkafoundry_net:
        ipv4_address: 172.232.1.1

  kusama_bob:
    build:
      context: .
    image: ubuntu:20.04
    volumes:
      - .:/usr/src/polkafoundry
    links:
      - "kusama_alice:alice"
    command: polkadot --chain /usr/local/kusama-local.json --bob --pruning archive --unsafe-ws-external --rpc-cors all --rpc-methods Unsafe --bootnodes '/ip4/172.232.1.1/tcp/30333/p2p/12D3KooWSL5Bycn5tmW1yQEZGhMJU42ParumTs2roEbFKhrgs8Ec'
    networks:
      polkafoundry_net:
        ipv4_address: 172.232.1.2

  kusama_charlie:
    build:
      context: .
    image: ubuntu:20.04
    volumes:
      - .:/usr/src/polkafoundry
    links:
      - "kusama_alice:alice"
    command: polkadot --chain /usr/local/kusama-local.json --charlie --pruning archive --unsafe-ws-external --rpc-cors all --rpc-methods Unsafe --bootnodes '/ip4/172.232.1.1/tcp/30333/p2p/12D3KooWSL5Bycn5tmW1yQEZGhMJU42ParumTs2roEbFKhrgs8Ec'
    networks:
      polkafoundry_net:
        ipv4_address: 172.232.1.3

  kusama_dave:
    build:
      context: .
    image: ubuntu:20.04
    volumes:
      - .:/usr/src/polkafoundry
    links:
      - "kusama_alice:alice"
    command: polkadot --chain /usr/local/kusama-local.json --dave --pruning archive --unsafe-ws-external --rpc-cors all --rpc-methods Unsafe --bootnodes '/ip4/172.232.1.1/tcp/30333/p2p/12D3KooWSL5Bycn5tmW1yQEZGhMJU42ParumTs2roEbFKhrgs8Ec'
    networks:
      polkafoundry_net:
        ipv4_address: 172.232.1.4

networks:
  polkafoundry_net:
    ipam:
      driver: default
      config:
        - subnet: 172.232.0.0/16
